import { createContext, useContext, useState, ReactNode } from "react";

export type Language = "en" | "es";

function detectInitialLang(): Language {
  const saved = localStorage.getItem("privaro-lang");
  if (saved === "es" || saved === "en") return saved;
  const browserLang = navigator.language || "";
  return browserLang.startsWith("es") ? "es" : "en";
}

interface LanguageContextType {
  lang: Language;
  setLang: (l: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    "nav.problem": "Problem",
    "nav.solution": "Solution",
    "nav.howItWorks": "How It Works",
    "nav.security": "Security",
    "nav.usecases": "Use Cases",
    "nav.usecases.legal": "Legal",
    "nav.usecases.health": "Healthcare",
    "nav.usecases.consulting": "Fintech & Finance",
    "nav.cta": "Request Demo",
    "hero.badge": "Built for regulated enterprise environments",
    "hero.title1": "Control How Your Organization",
    "hero.title2": "Uses AI",
    "hero.subtitle": "Privaro gives enterprises visibility and control over what data enters AI systems — enabling safe AI adoption at scale.",
    "hero.cta1": "Request Demo",
    "hero.cta2": "See How It Works",
    "hero.disclaimer": "Built for enterprise AI governance under GDPR, AI Act and sector regulations.",
    "urgency.title": "AI Adoption Is Growing Faster Than Compliance Controls.",
    "urgency.body1": "Organizations are adopting AI faster than they can govern it. Most companies lack visibility and control over what data employees send to AI systems.",
    "urgency.body2": "Privacy architecture must exist before AI scale.",
    "problem.label": "The Problem",
    "problem.title1": "Your Employees Are Using AI —",
    "problem.title2": "Without Governance",
    "problem.p1": "Employees increasingly use AI tools to analyze documents, summarize reports, and process client information. In most organizations, there is no visibility into what data is being sent to external AI systems.",
    "problem.p2": "Under GDPR and sector-specific regulations, responsibility remains fully with your organization.",
    "problem.p3": "AI models are powerful — but they were not designed as privacy infrastructure.",
    "problem.example": "Example: Contract review → client names, IBANs, medical data → external model inference.",
    "riskgap.title1": "There Is No Structural Layer Between",
    "riskgap.title2": "Your Data and the Model.",
    "riskgap.gap1": "Traditional DLP tools block AI usage instead of enabling it",
    "riskgap.gap2": "AI providers secure infrastructure — but not enterprise usage",
    "riskgap.gap3": "Organizations lack a governance layer for AI interactions",
    "riskgap.diagramLabel": "This is what happens today in most organizations.",
    "riskgap.conclusion": "That gap creates exposure.",
    "solution.label": "The Solution",
    "solution.title": "Meet Privaro — The Missing Layer.",
    "solution.subtitle": "Privaro creates a governance layer between enterprise and AI models, giving organizations visibility, control, and auditability over AI usage.",
    "solution.f1": "AI interactions are monitored in real time",
    "solution.f2": "Sensitive data is automatically protected",
    "solution.f3": "Policies control what data can enter AI",
    "solution.f4": "Full audit logs for compliance teams",
    "solution.conclusion1": "AI becomes usable.",
    "solution.conclusion2": "Risk becomes structurally manageable.",
    "how.label": "How It Works",
    "how.title1": "AI Governance by",
    "how.title2": "Architecture.",
    "how.step1.title": "Data Ingestion",
    "how.step1.desc": "Text or documents enter the Privaro layer.",
    "how.step2.title": "Semantic Detection",
    "how.step2.desc": "Advanced contextual detection identifies explicit and implicit sensitive data.",
    "how.step3.title": "Secure Tokenization",
    "how.step3.desc": "Data is anonymized or pseudonymized using secure reversible mechanisms.",
    "how.step4.title": "AI Proxy & Logging",
    "how.step4.desc": "Sanitized data is sent to the model. All actions are evidenced and certified by blockchain to facilitate audits.",
    "how.arch.enterprise": "Enterprise Data",
    "how.arch.enterpriseSub": "Contracts, Reports, Client Data",
    "how.arch.privaura": "Privaro Layer",
    "how.arch.aiModel": "AI Model",
    "how.badge.detection": "Detection",
    "how.badge.anonymization": "Anonymization",
    "how.badge.logging": "Blockchain Certified Logging",
    "dash.label": "Operational Control for AI Governance Teams",
    "dash.title1": "Built for Real",
    "dash.title2": "Enterprise Workflows.",
    "dash.subtitle": "A complete platform that detects, anonymizes, and audits sensitive data before it reaches any AI model.",
    "dash.sub1.title": "AI Governance Dashboard",
    "dash.sub1.desc": "Full visibility into how AI tools are used across the organization — including detected sensitive data, policy enforcement, and audit-ready logs.",
    "dash.sub2.title": "Governed AI Chat for Enterprise Teams",
    "dash.sub2.desc": "Your teams interact with AI through a privacy-first chat interface. Every message is analyzed in real time: sensitive data is detected and anonymized before reaching the model, ensuring zero data exposure without disrupting workflows.",
    "dash.sub3.title": "Centralized Control for All AI Providers",
    "dash.sub3.desc": "Connect OpenAI, Anthropic, DeepSeek or any compatible provider. Manage API keys, activate or deactivate engines, and control which models your organization uses — all through a centralized, secure configuration panel.",
    "comp.label": "Differentiation",
    "comp.title1": "Not a DLP. Not a Policy.",
    "comp.title2": "Infrastructure",
    "comp.subtitle": "Traditional DLP blocks workflows. LLM providers offer contractual assurances.\nPrivaro is not another security tool. It is the governance infrastructure for enterprise AI.",
    "comp.highlight": "It is the governance infrastructure for enterprise AI",
    "comp.col.feature": "Feature",
    "comp.col.dlp": "Traditional DLP",
    "comp.col.privaura": "Privaro",
    "comp.row1.feature": "AI Workflow",
    "comp.row1.dlp": "Blocks usage",
    "comp.row1.privaura": "Enables AI usage",
    "comp.row2.feature": "Detection Rules",
    "comp.row2.dlp": "Static rules",
    "comp.row2.privaura": "Context-aware detection",
    "comp.row3.feature": "LLM Compatibility",
    "comp.row3.dlp": "Not LLM-native",
    "comp.row3.privaura": "Designed for generative AI",
    "comp.row4.feature": "Audit & Compliance",
    "comp.row4.dlp": "Post-incident investigation",
    "comp.row4.privaura": "Certified by technology",
    "sec.label": "Security & Compliance",
    "sec.title1": "Enterprise AI-Governance",
    "sec.title2": "Infrastructure",
    "sec.b1": "Encryption in transit and at rest",
    "sec.b2": "Secure pseudonymization architecture",
    "sec.b3": "Audit logs certified on blockchain",
    "sec.b4": "GDPR-aligned design principles",
    "sec.b6": "Runtime policy enforcement",
    "sec.b5": "European regulatory alignment",
    "sec.layer1.title": "Encrypted Data In Transit",
    "sec.layer1.sub": "TLS 1.3 • End-to-end encryption",
    "sec.layer2.title": "Secure Tokenization Engine",
    "sec.layer2.sub": "AES-256 • Key Segmentation • Reversible Tokens",
    "sec.layer3.title": "Audit Log Storage",
    "sec.layer3.sub": "Immutable Hash Records • Tamper-proof",
    "blockchain.label": "Blockchain-Certified Audit",
    "blockchain.title1": "Every AI Interaction,",
    "blockchain.title2": "Immutably Certified",
    "blockchain.subtitle": "Privaro integrates with iCommunity Blockchain Services (iBS) to certify every AI interaction on-chain — creating tamper-proof, legally admissible digital evidence.",
    "blockchain.flow1": "Event Log",
    "blockchain.flow1sub": "AI interaction logged",
    "blockchain.flow2": "On-Chain Certification",
    "blockchain.flow2sub": "Hash certified via iBS",
    "blockchain.flow3": "Immutable Evidence",
    "blockchain.flow3sub": "Verifiable proof of compliance",
    "blockchain.poweredBy": "Powered by iCommunity Blockchain Services (iBS)",
    "blockchain.f1.title": "Immutable Audit Trail",
    "blockchain.f1.desc": "Every AI interaction generates a cryptographic hash certified on blockchain — no record can be altered or deleted.",
    "blockchain.f2.title": "Real-Time Certification",
    "blockchain.f2.desc": "Audit events are certified asynchronously in under 5 seconds via webhook, with zero impact on response latency.",
    "blockchain.f3.title": "Legally Admissible Evidence",
    "blockchain.f3.desc": "Blockchain-certified records serve as digital evidence for regulatory audits, litigation, and compliance investigations.",
    "blockchain.f4.title": "Independent Verification",
    "blockchain.f4.desc": "Any auditor can independently verify the integrity of audit records on the public Polygon network — no trust in Privaro required.",
    "cta.title1": "Adopt AI With",
    "cta.title2": "Confidence.",
    "cta.subtitle": "30-minute strategic walkthrough. No obligation.",
    "cta.btn": "Request Demo",
    "techbrief.title1": "Technical Architecture",
    "techbrief.title2": "Overview",
    "techbrief.text": "Download a concise technical brief explaining Privaro's architecture, data flow, and compliance model.",
    "techbrief.btn.download": "Download Architecture Paper",
    "techbrief.btn.demo": "Request Demo",
    "techbrief.btn.note": "Public document · No registration required",
    "techbrief.dialog.title": "Request Demo",
    "techbrief.dialog.subtitle": "Fill in the form below and request a customized demo.",
    "techbrief.dialog.submit": "Send Request",
    "techbrief.dialog.sending": "Sending...",
    "techbrief.dialog.thanks": "We'll send the technical brief to your email shortly.",
    "techbrief.dialog.error": "Something went wrong. Please try again.",
    "beta.label": "Early Access",
    "beta.title1": "Adopt AI With",
    "beta.title2": "Structural Protection.",
    "beta.subtitle": "AI adoption is accelerating. Data protection architecture has not kept pace. Privaro provides the missing infrastructure layer between your enterprise data and AI models.",
    "beta.whoFor": "Who It's For",
    "beta.a1": "Law Firms",
    "beta.a2": "Consulting Firms",
    "beta.a3": "Healthcare Groups",
    "beta.a4": "Regulated Enterprises",
    "beta.form.title": "Request Early Access",
    "beta.form.name": "Full Name*",
    "beta.form.company": "Company*",
    "beta.form.industry": "Industry*",
    "beta.form.role": "Role*",
    "beta.form.role.ciso": "CISO",
    "beta.form.role.cto": "CTO",
    "beta.form.role.dpo": "DPO",
    "beta.form.role.legal": "Legal",
    "beta.form.role.other": "Other",
    "beta.form.email": "Work Email*",
    "beta.form.aiQuestion": "What AI systems are you currently using and what is your biggest concern?",
    "beta.form.submit": "Request Demo",
    "beta.form.sending": "Sending...",
    "beta.form.disclaimer": "Limited early access for regulated enterprise teams.",
    "beta.form.error": "Something went wrong. Please try again.",
    "beta.thanks.title": "Thank you.",
    "beta.thanks.body": "We'll be in touch shortly with next steps.",
    "usecases.label": "Use Cases",
    "usecases.title1": "For organizations where",
    "usecases.title2": "AI usage must be governed",
    "usecases.subtitle": "Privaro provides structural AI governance across every sector where data sensitivity defines compliance.",
    "usecases.explore": "Explore use case",
    "usecases.legal.title": "Legal — Law Firms & Legal Teams",
    "usecases.legal.desc": "Protect privileged communications and prevent cross-border data transfer risks during AI-assisted contract analysis.",
    "usecases.health.title": "Healthcare — Clinical Organizations",
    "usecases.health.desc": "Prevent PHI exposure in AI summarization of clinical notes and patient records.",
    "usecases.finance.title": "Fintech & Finance — Banks, Insurers & Fintechs",
    "usecases.finance.desc": "Tokenize IBANs, KYC and AML data before AI inference under GDPR, PSD2 and DORA.",
    "nav.usecases.agents": "AI Agents",
    "usecases.agents.title": "AI Agents — Autonomous Workflows",
    "usecases.agents.desc": "Protect every agent step. PII tokenised before each LLM call. Blockchain-certified audit trail per interaction.",
    "agents.hero.badge": "New Use Case",
    "agents.hero.title1": "Privacy for",
    "agents.hero.title2": "AI Agents",
    "agents.hero.subtitle": "Your agents handle sensitive data on behalf of your clients. Privaro adds a privacy enforcement layer to every step — so you can close deals in regulated sectors without changing your architecture.",
    "agents.hero.trigger": "When your agents start touching real client data, compliance becomes a blocker. Privaro removes that blocker.",
    "agents.f1.title": "Step-Level Protection",
    "agents.f1.desc": "Every agent step is protected before sensitive data reaches the model. PII is detected, tokenised, and replaced with secure references. The agent works normally — the model never sees real data.",
    "agents.f2.title": "Verifiable Audit Trail (Blockchain-backed)",
    "agents.f2.desc": "Every agent step generates a tamper-proof, timestamped record. Each interaction produces an iBS signature on Fantom Opera Mainnet — immutable and verifiable. When a regulator asks what your agent did with client data — you have the proof.",
    "agents.f3.title": "Zero Latency Impact",
    "agents.f3.desc": "Privaro adds <50ms per step. Built for autonomous workflows where speed matters. Supports LangChain, CrewAI, n8n, and any agent framework that makes HTTP calls.",
    "agents.f4.title": "One-Line Integration",
    "agents.f4.desc": "Replace your LLM call with Privaro's agent endpoint. Works with Claude, GPT-4, Mistral, and Gemini. No SDK required — pure HTTP.",
    "agents.howItWorks": "How It Works",
    "agents.step1.title": "Agent triggers a step",
    "agents.step1.desc": "Calls POST /v1/agent/protect",
    "agents.step2.title": "Privaro detects PII",
    "agents.step2.desc": "Tokenises in <10ms",
    "agents.step3.title": "Clean payload sent to LLM",
    "agents.step3.desc": "Claude, GPT-4, Mistral, etc.",
    "agents.step4.title": "Response returned",
    "agents.step4.desc": "Optional de-tokenisation",
    "agents.step5.title": "iBS certificate generated",
    "agents.step5.desc": "Blockchain proof per step",
    "agents.frameworks": "Compatible Frameworks",
    "agents.without.1": "Agents blocked on sensitive data",
    "agents.without.2": "Deals slowed down by compliance concerns",
    "agents.without.3": "On-premise required for regulated clients",
    "agents.without.4": "No clear control of what the model sees",
    "agents.with.1": "Agents run on real client data safely",
    "agents.with.2": "Faster sales cycles",
    "agents.with.3": "No infrastructure changes required",
    "agents.with.4": "Full control over data exposure at runtime",
    "agents.comparison.title": "Without vs With Privaro",
    "agents.comparison.subtitle": "This is where most agent deployments break — and how Privaro fixes it.",
    "agents.comparison.without": "Without Privaro",
    "agents.comparison.with": "With Privaro",
    "agents.pricing": "Pricing",
    "agents.pricing.context": "Simple usage-based pricing — designed for AI builders and ISVs",
    "agents.plan1.name": "Agent Starter",
    "agents.plan1.steps": "50K agent steps",
    "agents.plan1.desc": "For prototyping & early integrations",
    "agents.plan2.name": "Agent Business",
    "agents.plan2.steps": "500K agent steps",
    "agents.plan2.desc": "For production agents & client deployments",
    "agents.plan3.name": "Agent Enterprise",
    "agents.plan3.price": "Custom",
    "agents.plan3.steps": "5M+ agent steps/month",
    "agents.plan3.desc": "For platforms, white-label & regulated environments",
    "agents.plan3.b1": "White-label ready",
    "agents.plan3.b2": "Multi-tenant environments",
    "agents.plan3.b3": "Custom SLA",
    "agents.plan3.b4": "Dedicated support",
    "agents.plan3.b5": "Custom deployment options",
    "agents.mostPopular": "Most Popular",
    "agents.tagline": "Privaro is not a feature. It's a deal enabler.",
    "agents.whyEmbed.title": "Why teams embed Privaro",
    "agents.why.1": "Use real client data without blocking your deals",
    "agents.why.2": "Close deals in regulated sectors (healthcare, legal, finance)",
    "agents.why.3": "Avoid costly on-prem deployments — compliance as a proxy layer",
    "agents.why.4": "Add a trust layer without changing your architecture",
    "agents.builders.title": "Built for AI Builders & Partners",
    "agents.builders.subtitle": "Integrate Privaro as a data control layer in your agents and unlock regulated use cases for your clients.",
    "agents.builders.cta": "Request Partner Access",
    "agents.partner.1": "Usage-based pricing — you control the margin",
    "agents.partner.2": "White-label available on Enterprise",
    "agents.partner.3": "No infrastructure changes for your clients",
    "agents.partner.4": "Built for multi-client environments",
    "agents.partner.5": "Verifiable audit trail (blockchain-backed)",
    "agents.usecases.title": "Typical use cases",
    "agents.usecase.1": "AI agents for compliance platforms",
    "agents.usecase.2": "Automation over CRM + documents",
    "agents.usecase.3": "Customer-facing workflows with sensitive data",
    "agents.cta": "Request Early Access",
    "agents.cta.sub": "Deploys in minutes. No infra changes.",
    "footer.rights": "All rights reserved.",
    "footer.tagline": "Privacy infrastructure for enterprise AI.",
    "footer.by": "Built by",
    "footer.privacy": "Privacy Policy",
    "footer.terms": "Terms of Use",
    "footer.contact": "Contact",
    "privacy.title": "Privacy Policy",
    "privacy.lastUpdated": "Last updated: March 2026",
    "privacy.s1.title": "1. Data Controller",
    "privacy.s1.body": "The data controller is iCommunity Labs & Tech S.L., operating under the brand Privaro. For any privacy-related inquiries, please contact us at privacy@privaro.ai.",
    "privacy.s2.title": "2. Data We Collect",
    "privacy.s2.body": "We collect personal data you provide when requesting a demo or early access, including your name, company, work email, role, and industry. We also collect anonymous usage analytics to improve our services.",
    "privacy.s3.title": "3. Purpose and Legal Basis",
    "privacy.s3.body": "Your data is processed to respond to your inquiries, provide access to our platform, and send relevant communications. The legal basis is your consent and our legitimate interest in improving our services.",
    "privacy.s4.title": "4. Data Sharing",
    "privacy.s4.body": "We do not sell or share your personal data with third parties for marketing purposes. Data may be processed by service providers acting as data processors under appropriate contractual safeguards.",
    "privacy.s5.title": "5. Your Rights",
    "privacy.s5.body": "Under GDPR, you have the right to access, rectify, erase, restrict processing, data portability, and object to processing of your personal data. To exercise these rights, contact privacy@privaro.ai.",
    "privacy.s6.title": "6. Data Retention",
    "privacy.s6.body": "We retain your personal data only for as long as necessary to fulfill the purposes described above, or as required by applicable law. You may request deletion of your data at any time.",
    "terms.title": "Terms of Use",
    "terms.lastUpdated": "Last updated: March 2026",
    "terms.s1.title": "1. Acceptance of Terms",
    "terms.s1.body": "By accessing or using Privaro's website and services, you agree to be bound by these Terms of Use. If you do not agree, please do not use our services.",
    "terms.s2.title": "2. Description of Service",
    "terms.s2.body": "Privaro provides an AI governance infrastructure platform that enables enterprises to control, monitor, and audit AI usage while protecting sensitive data. Access to the platform is subject to a separate enterprise agreement.",
    "terms.s3.title": "3. Intellectual Property",
    "terms.s3.body": "All content, trademarks, and technology on this website are the property of iCommunity Labs & Tech S.L. You may not reproduce, distribute, or create derivative works without prior written consent.",
    "terms.s4.title": "4. User Obligations",
    "terms.s4.body": "You agree to use the service in compliance with all applicable laws and regulations. You are responsible for maintaining the confidentiality of your account credentials and for all activities under your account.",
    "terms.s5.title": "5. Limitation of Liability",
    "terms.s5.body": "Privaro is provided 'as is' without warranties of any kind. To the maximum extent permitted by law, iCommunity Labs & Tech S.L. shall not be liable for any indirect, incidental, or consequential damages arising from your use of the service.",
    "terms.s6.title": "6. Governing Law",
    "terms.s6.body": "These terms are governed by the laws of Spain. Any disputes shall be subject to the exclusive jurisdiction of the courts of Madrid, Spain.",
    "auth.signin": "Sign in",
    "auth.signup": "Create account",
    "auth.forgot": "Reset password",
    "auth.signin.desc": "Access your privacy dashboard",
    "auth.signup.desc": "Set up your organization",
    "auth.forgot.desc": "We'll send you a reset link",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.orgName": "Organization name",
    "auth.fullName": "Full name",
    "auth.forgotLink": "Forgot password?",
    "auth.sendReset": "Send reset link",
    "auth.sending": "Sending...",
    "auth.loading": "Loading...",
    "auth.backToSignin": "Back to sign in",
    "auth.noAccount": "Don't have an account?",
    "auth.hasAccount": "Already have an account?",
    "auth.accountCreated": "Account created",
    "auth.checkEmail": "Check your email to verify your account, then sign in.",
    "auth.emailSent": "Email sent",
    "auth.checkInbox": "Check your inbox for a password reset link.",
    "emailConfirmed.title": "Account verified!",
    "emailConfirmed.desc": "Your email has been confirmed successfully. You can now sign in to your account.",
    "emailConfirmed.redirect": "Redirecting to sign in…",
    "reset.title": "Reset your password",
    "reset.desc": "Enter your new password below",
    "reset.newPassword": "New password",
    "reset.confirmPassword": "Confirm password",
    "reset.update": "Update password",
    "reset.updating": "Updating...",
    "reset.verifying": "Verifying reset link…",
    "reset.noMatch": "Passwords do not match",
    "reset.success": "Password updated",
    "reset.successDesc": "You can now sign in with your new password.",
    "secpage.hero.badge": "Security & Compliance",
    "secpage.hero.title1": "Enterprise-grade security",
    "secpage.hero.title2": "by design, not by policy",
    "secpage.hero.desc": "Privaro's privacy infrastructure is built on the principle that security controls must be architectural — not application-layer afterthoughts.",
    "secpage.badge.aes": "AES-256-GCM Encryption",
    "secpage.badge.blockchain": "Blockchain-Certified Audit Trail",
    "secpage.badge.gdpr": "GDPR Art.5 Compliant",
    "secpage.badge.tls": "TLS 1.3 Enforced",
    "secpage.badge.soc2": "SOC2 Type I — In Preparation",
    "secpage.badge.iso": "ISO 27001 — In Preparation",
    "secpage.arch.label": "Architecture",
    "secpage.arch.title": "Security built into every layer",
    "secpage.arch.desc": "Privacy controls are applied at the network layer — before any data reaches an AI model. This is architecturally superior to post-processing or application-level filtering.",
    "secpage.pillar1.title": "Zero Raw PII Exposure",
    "secpage.pillar1.desc": "No plaintext personal data is ever transmitted to an AI provider. Tokenization occurs within Privaro's trusted boundary. Original values are stored exclusively in the encrypted vault.",
    "secpage.pillar2.title": "Verifiable Compliance Evidence",
    "secpage.pillar2.desc": "Audit records are cryptographically certified on Fantom Opera Mainnet. Compliance is demonstrable to regulators independently of Privaro's infrastructure.",
    "secpage.pillar3.title": "Defense in Depth",
    "secpage.pillar3.desc": "Security controls are layered: TLS 1.3 at the network level, JWT + API key auth at the application level, Row Level Security at the database level, AES-256-GCM at the data level.",
    "secpage.pillar4.title": "Policy-Driven Governance",
    "secpage.pillar4.desc": "Every entity type has a configurable action: tokenise, anonymise, or block. Sector presets for Legal, Healthcare, Fintech, HR, and Port Environmental are built-in.",
    "secpage.pillar5.title": "Agent Governance",
    "secpage.pillar5.desc": "Autonomous AI agents operate under the same privacy policies as human users. The Agent API enforces governance at every step of automated workflows — EU AI Act compliant.",
    "secpage.pillar6.title": "EU Data Residency",
    "secpage.pillar6.desc": "All infrastructure is hosted in EU regions by default. Database in eu-central-1, proxy in europe-west4. No data leaves the EU without explicit customer configuration.",
    "secpage.controls.label": "Controls",
    "secpage.controls.title": "Implemented security controls",
    "secpage.controls.desc": "Key technical controls aligned to ISO/IEC 27001:2022 Annex A and SOC2 Trust Services Criteria.",
    "secpage.ctrl1.desc": "AES-256-GCM encryption for all token originals. 12-byte random nonce per operation. Per-org key segmentation.",
    "secpage.ctrl2.desc": "Row Level Security enforces org isolation at the database level. All queries filtered by org_id.",
    "secpage.ctrl3.desc": "API keys stored as SHA-256 hashes. Plaintext never persisted. JWT verification on all frontend calls.",
    "secpage.ctrl4.desc": "Immutable audit logs with blockchain certification. UPDATE restricted to ibs_* columns only via RLS policy.",
    "secpage.ctrl5.desc": "TLS 1.3 enforced on all connections. No TLS 1.0 or 1.1 accepted. CORS configured per environment.",
    "secpage.ctrl6.desc": "Blockchain-certified audit trail. Every PII interaction generates a tamper-evident record on Fantom Opera Mainnet.",
    "secpage.ctrl7.desc": "Four-tier role model: viewer, developer, dpo, admin. Cumulative permissions enforced at DB level, not application layer.",
    "secpage.ctrl8.desc": "Secure development lifecycle: GitHub-based code review, Railway deployment pipeline, automated health checks.",
    "secpage.status.implemented": "✓ Implemented",
    "secpage.status.progress": "⟳ In Progress",
    "secpage.compliance.label": "Compliance",
    "secpage.compliance.title": "Regulatory coverage",
    "secpage.compliance.desc": "Privaro is designed to help enterprise customers meet their data protection obligations under multiple regulatory frameworks.",
    "secpage.table.regulation": "Regulation",
    "secpage.table.scope": "Scope",
    "secpage.table.coverage": "Privaro Coverage",
    "secpage.table.status": "Status",
    "secpage.reg1.scope": "Data minimization, purpose limitation",
    "secpage.reg1.coverage": "Policy engine enforces minimum necessary processing. No raw PII to LLMs.",
    "secpage.reg2.scope": "Special category data (health, biometric)",
    "secpage.reg2.coverage": "health_record entity blocked or anonymised by default in Healthcare/HR presets.",
    "secpage.reg3.scope": "Records of processing activities",
    "secpage.reg3.coverage": "Blockchain-certified audit log per interaction. DPO report export with TX hashes.",
    "secpage.reg4.scope": "High-risk AI systems, human oversight",
    "secpage.reg4.coverage": "Agent API enforces governance on autonomous agents. Per-entity action in audit logs.",
    "secpage.reg5.scope": "Payment data protection",
    "secpage.reg5.coverage": "IBAN and card numbers tokenized before any LLM call. Fintech preset built-in.",
    "secpage.reg6.scope": "Protected Health Information",
    "secpage.reg6.coverage": "PHI tokenized/anonymised. Blockchain audit trail per PHI access. Healthcare preset.",
    "secpage.reg7.scope": "Information security management",
    "secpage.reg7.coverage": "83% of Annex A controls implemented. ISMS documentation in progress.",
    "secpage.reg8.scope": "Security, Confidentiality trust criteria",
    "secpage.reg8.coverage": "Controls implemented. Formal audit preparation in progress for Q3 2026.",
    "secpage.status.covered": "Covered",
    "secpage.status.inprogress": "In Progress",
    "secpage.blockchain.label": "Blockchain Audit Trail",
    "secpage.blockchain.title": "Tamper-proof compliance evidence",
    "secpage.blockchain.desc": "Every audit event is cryptographically certified on Fantom Opera Mainnet — independently verifiable by regulators, auditors, and data subjects.",
    "secpage.blockchain.howTitle": "How it works",
    "secpage.blockchain.howP1": "Every PII detection event generates an audit record. The record's SHA-512 hash is certified on Fantom Opera Mainnet via iBS API. The resulting blockchain TX hash is stored in the audit log.",
    "secpage.blockchain.howP2": "Batch certification reduces costs: up to 100 audit events are certified in a single blockchain transaction every 5 minutes.",
    "secpage.blockchain.verifyTitle": "Public verifiability",
    "secpage.blockchain.verifyDesc": "Any certified event can be independently verified using the TX hash — no access to Privaro's infrastructure required.",
    "secpage.stat1.label": "Opera Mainnet blockchain",
    "secpage.stat2.label": "Avg. certification time",
    "secpage.stat3.label": "Batch efficiency (events per TX)",
    "secpage.stat4.label": "Hashing algorithm",
    "secpage.docs.label": "Policy Documents",
    "secpage.docs.title": "Security policies & procedures",
    "secpage.docs.desc": "Privaro maintains a complete set of security policies aligned to ISO 27001 and SOC2 requirements. Available to enterprise customers under NDA.",
    "secpage.doc1.title": "Information Security Policy",
    "secpage.doc2.title": "Data Processing & Privacy Policy",
    "secpage.doc3.title": "Security Controls Register (ISO 27001 Annex A)",
    "secpage.doc4.title": "Incident Response Plan",
    "secpage.doc5.title": "Business Continuity & Availability Policy",
    "secpage.doc6.title": "Data Processing Agreement (DPA)",
    "secpage.cta.title": "Security questions?",
    "secpage.cta.desc": "Our team is available to answer security questionnaires, complete vendor assessments, or schedule a technical deep-dive.",
    "secpage.cta.contact": "Contact Security Team",
    "secpage.cta.download": "Download Policy Documents",
  },
  es: {
    "nav.problem": "Problema", "nav.solution": "Solución", "nav.howItWorks": "Cómo Funciona", "nav.security": "Seguridad", "nav.usecases": "Casos de Uso", "nav.usecases.legal": "Legal", "nav.usecases.health": "Salud", "nav.usecases.consulting": "Fintech y Finanzas", "nav.cta": "Solicitar Demo",
    "hero.badge": "Diseñado para entornos empresariales regulados", "hero.title1": "Controla Cómo Tu Organización", "hero.title2": "Usa la IA", "hero.subtitle": "Privaro ofrece a las empresas visibilidad y control sobre qué datos entran en los sistemas de IA — permitiendo una adopción segura de IA a escala.", "hero.cta1": "Solicitar demo", "hero.cta2": "Ver Cómo Funciona", "hero.disclaimer": "Diseñado para GDPR, AI Act y regulación sectorial.",
    "urgency.title": "La Adopción de IA Crece Más Rápido que los Controles de Cumplimiento.", "urgency.body1": "Las organizaciones adoptan IA más rápido de lo que pueden gobernarla. La mayoría carece de visibilidad y control sobre qué datos envían sus empleados a los sistemas de IA.", "urgency.body2": "La arquitectura de privacidad debe existir antes del escalado de IA.",
    "problem.label": "El Problema", "problem.title1": "Tus Empleados Usan IA —", "problem.title2": "Sin Governance", "problem.p1": "Los empleados usan cada vez más herramientas de IA para analizar documentos, resumir informes y procesar información de clientes. En la mayoría de organizaciones, no hay visibilidad sobre qué datos se envían a sistemas de IA externos.", "problem.p2": "Bajo el RGPD y regulaciones sectoriales, la responsabilidad recae completamente en tu organización.", "problem.p3": "Los modelos de IA son poderosos — pero no fueron diseñados como infraestructura de privacidad.", "problem.example": "Ejemplo: Revisión de contratos → nombres de clientes, IBANs, datos médicos → inferencia en modelo externo.",
    "riskgap.title1": "No Existe una Capa Estructural Entre", "riskgap.title2": "Tus Datos y el Modelo.", "riskgap.gap1": "Las herramientas DLP tradicionales bloquean el uso de IA en lugar de habilitarlo", "riskgap.gap2": "Los proveedores de IA aseguran la infraestructura — pero no el uso empresarial", "riskgap.gap3": "Las organizaciones carecen de una capa de gobernanza para las interacciones con IA", "riskgap.diagramLabel": "Esto es lo que ocurre hoy en la mayoría de organizaciones.", "riskgap.conclusion": "Esa brecha crea exposición.",
    "solution.label": "La Solución", "solution.title": "Conoce Privaro — La Capa que Faltaba.", "solution.subtitle": "Privaro crea una capa de gobernanza entre los usuarios empresariales y los sistemas de IA, brindando a las organizaciones visibilidad, control y auditabilidad sobre el uso de IA.", "solution.f1": "Las interacciones con IA se monitorean en tiempo real", "solution.f2": "Los datos sensibles se protegen automáticamente", "solution.f3": "Las políticas controlan qué datos pueden entrar a la IA", "solution.f4": "Logs de auditoría completos para equipos de cumplimiento", "solution.conclusion1": "La IA se vuelve utilizable.", "solution.conclusion2": "El riesgo se vuelve estructuralmente manejable.",
    "how.label": "Cómo Funciona", "how.title1": "AI Governance por", "how.title2": "Arquitectura.", "how.step1.title": "Ingesta de Datos", "how.step1.desc": "Texto o documentos entran en la capa Privaro.", "how.step2.title": "Detección Semántica", "how.step2.desc": "Detección contextual avanzada que identifica datos sensibles explícitos e implícitos.", "how.step3.title": "Tokenización Segura", "how.step3.desc": "Los datos se anonimizan o seudonomizan mediante mecanismos reversibles seguros.", "how.step4.title": "Proxy de IA y Registro", "how.step4.desc": "Los datos saneados se envían al modelo. Todas las acciones son evidenciadas y certificadas por blockchain para facilitar las auditorías.", "how.arch.enterprise": "Datos Empresariales", "how.arch.enterpriseSub": "Contratos, Informes, Datos de Clientes", "how.arch.privaura": "Capa Privaro", "how.arch.aiModel": "Modelo de IA", "how.badge.detection": "Detección", "how.badge.anonymization": "Anonimización", "how.badge.logging": "Registro Certificado por Blockchain",
    "dash.label": "Control Operativo para Equipos de Governance de IA", "dash.title1": "Diseñado para Flujos", "dash.title2": "Empresariales Reales.", "dash.subtitle": "Una plataforma completa que detecta, anonimiza y audita datos sensibles antes de que lleguen a cualquier modelo de IA.", "dash.sub1.title": "Dashboard de AI Governance", "dash.sub1.desc": "Visibilidad completa sobre cómo se usan las herramientas de IA en la organización — incluyendo datos sensibles detectados, aplicación de políticas y logs listos para auditoría.", "dash.sub2.title": "Chat IA Gobernado para Equipos Empresariales", "dash.sub2.desc": "Tus equipos interactúan con IA a través de una interfaz de chat con privacidad por diseño. Cada mensaje se analiza en tiempo real: los datos sensibles se detectan y anonimizan antes de llegar al modelo, garantizando cero exposición sin interrumpir los flujos de trabajo.", "dash.sub3.title": "Control Centralizado para Todos los Proveedores de IA", "dash.sub3.desc": "Conecta OpenAI, Anthropic, DeepSeek o cualquier proveedor compatible. Gestiona claves API, activa o desactiva motores y controla qué modelos usa tu organización — todo desde un panel de configuración centralizado y seguro.",
    "comp.label": "Diferenciación", "comp.title1": "No es un DLP. No es una Política.", "comp.title2": "Es Infraestructura.", "comp.subtitle": "El DLP tradicional bloquea los flujos de trabajo. Los proveedores de LLM ofrecen garantías contractuales.\nPrivaro no es otra herramienta de seguridad. Es la infraestructura de governance para IA empresarial.", "comp.highlight": "Es la infraestructura de governance para IA empresarial", "comp.col.feature": "Característica", "comp.col.dlp": "DLP Tradicional", "comp.col.privaura": "Privaro", "comp.row1.feature": "Flujo de IA", "comp.row1.dlp": "Bloquea el uso", "comp.row1.privaura": "Habilita el uso de IA", "comp.row2.feature": "Reglas de Detección", "comp.row2.dlp": "Reglas estáticas", "comp.row2.privaura": "Detección contextual", "comp.row3.feature": "Compatibilidad LLM", "comp.row3.dlp": "No nativo para LLM", "comp.row3.privaura": "Diseñado para IA generativa", "comp.row4.feature": "Auditoría y Cumplimiento", "comp.row4.dlp": "Investigación post-incidente", "comp.row4.privaura": "Certificada por tecnología",
    "sec.label": "Seguridad y Cumplimiento", "sec.title1": "Infraestructura de AI-Governance", "sec.title2": "Empresarial.", "sec.b1": "Cifrado en tránsito y en reposo", "sec.b2": "Arquitectura de seudonimización segura", "sec.b3": "Registros de auditoría certificados en blockchain", "sec.b4": "Principios de diseño alineados con el RGPD", "sec.b6": "Aplicación de políticas en tiempo real", "sec.b5": "Alineación con la regulación europea", "sec.layer1.title": "Datos Cifrados en Tránsito", "sec.layer1.sub": "TLS 1.3 • Cifrado extremo a extremo", "sec.layer2.title": "Motor de Tokenización Segura", "sec.layer2.sub": "AES-256 • Segmentación de Claves • Tokens Reversibles", "sec.layer3.title": "Almacenamiento de Registros de Auditoría", "sec.layer3.sub": "Registros de Hash Inmutables • A prueba de manipulaciones",
    "blockchain.label": "Interacciones Certificadas por Blockchain", "blockchain.title1": "Cada Interacción con IA,", "blockchain.title2": "Certificada de Forma Inmutable", "blockchain.subtitle": "Privaro se integra con iCommunity Blockchain Services (iBS) para certificar cada interacción con IA on-chain — creando evidencia digital inmutable y legalmente admisible.", "blockchain.flow1": "Registro de Evento", "blockchain.flow1sub": "Interacción con IA registrada", "blockchain.flow2": "Certificación On-Chain", "blockchain.flow2sub": "Hash certificado vía iBS", "blockchain.flow3": "Evidencia Inmutable", "blockchain.flow3sub": "Prueba verificable de cumplimiento", "blockchain.poweredBy": "Impulsado por iCommunity Blockchain Services (iBS)", "blockchain.f1.title": "Registro de Auditoría Inmutable", "blockchain.f1.desc": "Cada interacción con IA genera un hash criptográfico certificado en blockchain — ningún registro puede ser alterado o eliminado.", "blockchain.f2.title": "Certificación en Tiempo Real", "blockchain.f2.desc": "Los eventos de auditoría se certifican de forma asíncrona en menos de 5 segundos vía webhook, sin impacto en la latencia de respuesta.", "blockchain.f3.title": "Evidencia Legalmente Admisible", "blockchain.f3.desc": "Los registros certificados por blockchain sirven como evidencia digital para auditorías regulatorias, litigios e investigaciones de cumplimiento.", "blockchain.f4.title": "Verificación Independiente", "blockchain.f4.desc": "Cualquier auditor puede verificar independientemente la integridad de los registros en la red pública de Polygon — sin necesidad de confiar en Privaro.",
    "cta.title1": "Adopta IA Con", "cta.title2": "Confianza.", "cta.subtitle": "Sesión estratégica de 30 minutos. Sin compromiso.", "cta.btn": "Solicitar demo",
    "techbrief.title1": "Visión General de la", "techbrief.title2": "Arquitectura Técnica", "techbrief.text": "Descarga un resumen técnico conciso que explica la arquitectura de Privaro, el flujo de datos y el modelo de cumplimiento.", "techbrief.btn.download": "Descargar Architecture Paper", "techbrief.btn.demo": "Solicitar Demo", "techbrief.btn.note": "Documento público · Sin registro necesario", "techbrief.dialog.title": "Solicitar Demo", "techbrief.dialog.subtitle": "Completa el formulario y solicita una demo personalizada.", "techbrief.dialog.submit": "Enviar Solicitud", "techbrief.dialog.sending": "Enviando...", "techbrief.dialog.thanks": "Te enviaremos el resumen técnico a tu email en breve.", "techbrief.dialog.error": "Algo salió mal. Inténtalo de nuevo.",
    "beta.label": "Acceso Anticipado", "beta.title1": "Adopta IA Con", "beta.title2": "Protección Estructural.", "beta.subtitle": "La adopción de IA se acelera. La arquitectura de protección de datos no ha seguido el ritmo. Privaro proporciona la capa de infraestructura que faltaba entre tus datos empresariales y los modelos de IA.", "beta.whoFor": "Para Quién Es", "beta.a1": "Despachos de Abogados", "beta.a2": "Firmas de Consultoría", "beta.a3": "Grupos Sanitarios", "beta.a4": "Empresas Reguladas", "beta.form.title": "Solicitar Acceso Anticipado", "beta.form.name": "Nombre Completo*", "beta.form.company": "Empresa*", "beta.form.industry": "Sector*", "beta.form.role": "Cargo*", "beta.form.role.ciso": "CISO", "beta.form.role.cto": "CTO", "beta.form.role.dpo": "DPO", "beta.form.role.legal": "Legal", "beta.form.role.other": "Otro", "beta.form.email": "Email Corporativo*", "beta.form.aiQuestion": "¿Qué sistemas de IA estás usando actualmente y cuál es tu mayor preocupación?", "beta.form.submit": "Solicitar demo", "beta.form.sending": "Enviando...", "beta.form.disclaimer": "Acceso anticipado limitado para equipos empresariales regulados.", "beta.form.error": "Algo salió mal. Inténtalo de nuevo.", "beta.thanks.title": "Gracias.", "beta.thanks.body": "Nos pondremos en contacto pronto con los próximos pasos.",
    "usecases.label": "Casos de Uso", "usecases.title1": "Para organizaciones donde", "usecases.title2": "el uso de IA debe ser gobernado", "usecases.subtitle": "Privaro proporciona governance estructural de IA en todos los sectores donde la sensibilidad de datos define el cumplimiento.", "usecases.explore": "Ver caso de uso", "usecases.legal.title": "Legal — Despachos y Equipos Jurídicos", "usecases.legal.desc": "Protege comunicaciones privilegiadas y previene riesgos de transferencia transfronteriza de datos en el análisis de contratos asistido por IA.", "usecases.health.title": "Salud — Organizaciones Clínicas", "usecases.health.desc": "Previene la exposición de PHI en la sumarización por IA de notas clínicas e historiales de pacientes.", "usecases.finance.title": "Fintech y Finanzas — Bancos, Aseguradoras y Fintech", "usecases.finance.desc": "Tokeniza IBANs, datos KYC y AML antes de la inferencia por IA bajo GDPR, PSD2 y DORA.",
    "nav.usecases.agents": "Agentes IA", "usecases.agents.title": "Agentes IA — Flujos Autónomos", "usecases.agents.desc": "Protege cada paso del agente. PII tokenizado antes de cada llamada al LLM. Trazabilidad certificada en blockchain.",
    "agents.hero.badge": "Nuevo Caso de Uso",
    "agents.hero.title1": "Privacidad para",
    "agents.hero.title2": "Agentes IA",
    "agents.hero.subtitle": "Tus agentes manejan datos sensibles en nombre de tus clientes. Privaro añade una capa de privacidad en cada paso — para que puedas cerrar acuerdos en sectores regulados sin cambiar tu arquitectura.",
    "agents.f1.title": "Protección por Paso",
    "agents.f1.desc": "Privaro intercepta cada llamada a /v1/agent/protect antes de que llegue al LLM. El PII se detecta, tokeniza y reemplaza con referencias seguras. El agente funciona con normalidad — el modelo nunca ve datos reales.",
    "agents.f2.title": "Certificación Blockchain (iBS)",
    "agents.f2.desc": "Cada paso del agente genera una firma iBS en Fantom Opera Mainnet. Inmutable, con marca temporal, a prueba de manipulaciones. Cuando un regulador pregunte qué hizo tu agente con los datos del cliente — tienes la prueba.",
    "agents.f3.title": "Impacto Cero en Latencia",
    "agents.f3.desc": "Privaro añade <50ms por paso. Diseñado para flujos autónomos donde la velocidad importa. Compatible con LangChain, CrewAI, n8n y cualquier framework de agentes que haga llamadas HTTP.",
    "agents.f4.title": "Integración en Una Línea",
    "agents.f4.desc": "Reemplaza tu llamada al LLM con el endpoint de agentes de Privaro. Compatible con Claude, GPT-4, Mistral y Gemini. Sin SDK necesario — HTTP puro.",
    "agents.howItWorks": "Cómo Funciona",
    "agents.step1.title": "El agente ejecuta un paso",
    "agents.step1.desc": "Llama a POST /v1/agent/protect",
    "agents.step2.title": "Privaro detecta PII",
    "agents.step2.desc": "Tokeniza en <10ms",
    "agents.step3.title": "Payload limpio enviado al LLM",
    "agents.step3.desc": "Claude, GPT-4, Mistral, etc.",
    "agents.step4.title": "Respuesta devuelta",
    "agents.step4.desc": "De-tokenización opcional",
    "agents.step5.title": "Certificado iBS generado",
    "agents.step5.desc": "Prueba blockchain por paso",
    "agents.frameworks": "Frameworks Compatibles",
    "agents.without.1": "Agentes bloqueados por datos sensibles",
    "agents.without.2": "Ventas ralentizadas por requisitos de compliance",
    "agents.without.3": "On-premise obligatorio para clientes regulados",
    "agents.without.4": "Sin control claro de lo que ve el modelo",
    "agents.with.1": "Los agentes trabajan con datos reales de forma segura",
    "agents.with.2": "Ciclos de venta más rápidos",
    "agents.with.3": "Sin cambios de infraestructura necesarios",
    "agents.with.4": "Control total sobre la exposición de datos en tiempo de ejecución",
    "agents.comparison.title": "Sin Privaro vs Con Privaro",
    "agents.comparison.without": "Sin Privaro",
    "agents.comparison.with": "Con Privaro",
    "agents.pricing": "Precios",
    "agents.plan1.name": "Agent Starter",
    "agents.plan1.steps": "50K pasos de agente",
    "agents.plan1.desc": "Para prototipado e integraciones iniciales",
    "agents.plan2.name": "Agent Business",
    "agents.plan2.steps": "500K pasos de agente",
    "agents.plan2.desc": "Para agentes en producción y despliegues con clientes",
    "agents.plan3.name": "Agent Enterprise",
    "agents.plan3.price": "Personalizado",
    "agents.plan3.steps": "5M+ pasos de agente/mes",
    "agents.plan3.desc": "Para plataformas, white-label y entornos regulados",
    "agents.plan3.b1": "White-label ready",
    "agents.plan3.b2": "Entornos multi-tenant",
    "agents.plan3.b3": "SLA personalizado",
    "agents.plan3.b4": "Soporte dedicado",
    "agents.plan3.b5": "Opciones de despliegue personalizadas",
    "agents.mostPopular": "Más Popular",
    "agents.tagline": "Privaro no es una funcionalidad. Es un habilitador de negocio.",
    "agents.whyEmbed.title": "Por qué los equipos integran Privaro",
    "agents.why.1": "Usa datos reales de clientes sin bloquear tus acuerdos",
    "agents.why.2": "Cierra acuerdos en sectores regulados (salud, legal, finanzas)",
    "agents.why.3": "Evita costosos despliegues on-prem — compliance como capa proxy",
    "agents.why.4": "Añade una capa de confianza sin cambiar tu arquitectura",
    "agents.builders.title": "Diseñado para AI Builders y Partners",
    "agents.builders.subtitle": "Integra Privaro como capa de control de datos en tus agentes y desbloquea casos de uso regulados para tus clientes.",
    "agents.builders.cta": "Solicitar Acceso Partner",
    "agents.partner.1": "Precios por uso — tú controlas el margen",
    "agents.partner.2": "White-label disponible en Enterprise",
    "agents.partner.3": "Sin cambios de infraestructura para tus clientes",
    "agents.partner.4": "Diseñado para entornos multi-cliente",
    "agents.partner.5": "Trazabilidad verificable (respaldada por blockchain)",
    "agents.usecases.title": "Casos de uso típicos",
    "agents.usecase.1": "Agentes IA para plataformas de compliance",
    "agents.usecase.2": "Automatización sobre CRM + documentos",
    "agents.usecase.3": "Flujos con clientes que manejan datos sensibles",
    "agents.cta": "Solicitar Acceso Anticipado",
    "agents.cta.sub": "Se despliega en minutos. Sin cambios de infraestructura.",
    "footer.rights": "Todos los derechos reservados.", "footer.tagline": "Infraestructura de privacidad para IA empresarial.", "footer.by": "Desarrollado por", "footer.privacy": "Política de Privacidad", "footer.terms": "Términos de Uso", "footer.contact": "Contacto",
    "privacy.title": "Política de Privacidad", "privacy.lastUpdated": "Última actualización: marzo 2026", "privacy.s1.title": "1. Responsable del Tratamiento", "privacy.s1.body": "El responsable del tratamiento es iCommunity Labs & Tech S.L., operando bajo la marca Privaro. Para consultas relacionadas con privacidad, contacta con privacy@privaro.ai.", "privacy.s2.title": "2. Datos que Recopilamos", "privacy.s2.body": "Recopilamos los datos personales que proporcionas al solicitar una demo o acceso anticipado, incluyendo tu nombre, empresa, email corporativo, cargo y sector. También recopilamos analíticas de uso anónimas para mejorar nuestros servicios.", "privacy.s3.title": "3. Finalidad y Base Legal", "privacy.s3.body": "Tus datos se procesan para responder a tus consultas, proporcionar acceso a nuestra plataforma y enviar comunicaciones relevantes. La base legal es tu consentimiento y nuestro interés legítimo en mejorar nuestros servicios.", "privacy.s4.title": "4. Cesión de Datos", "privacy.s4.body": "No vendemos ni compartimos tus datos personales con terceros con fines de marketing. Los datos pueden ser procesados por proveedores de servicios que actúan como encargados del tratamiento bajo las garantías contractuales adecuadas.", "privacy.s5.title": "5. Tus Derechos", "privacy.s5.body": "Bajo el RGPD, tienes derecho a acceder, rectificar, suprimir, limitar el tratamiento, portabilidad y oponerte al tratamiento de tus datos personales. Para ejercer estos derechos, contacta con privacy@privaro.ai.", "privacy.s6.title": "6. Conservación de Datos", "privacy.s6.body": "Conservamos tus datos personales solo durante el tiempo necesario para cumplir con los fines descritos anteriormente, o según lo exija la legislación aplicable. Puedes solicitar la eliminación de tus datos en cualquier momento.",
    "terms.title": "Términos de Uso", "terms.lastUpdated": "Última actualización: marzo 2026", "terms.s1.title": "1. Aceptación de los Términos", "terms.s1.body": "Al acceder o utilizar el sitio web y los servicios de Privaro, aceptas quedar vinculado por estos Términos de Uso. Si no estás de acuerdo, por favor no utilices nuestros servicios.", "terms.s2.title": "2. Descripción del Servicio", "terms.s2.body": "Privaro proporciona una plataforma de infraestructura de AI governance que permite a las empresas controlar, monitorizar y auditar el uso de IA mientras protegen datos sensibles. El acceso a la plataforma está sujeto a un acuerdo empresarial independiente.", "terms.s3.title": "3. Propiedad Intelectual", "terms.s3.body": "Todo el contenido, marcas y tecnología de este sitio web son propiedad de iCommunity Labs & Tech S.L. No puedes reproducir, distribuir ni crear obras derivadas sin consentimiento previo por escrito.", "terms.s4.title": "4. Obligaciones del Usuario", "terms.s4.body": "Te comprometes a utilizar el servicio en cumplimiento con todas las leyes y regulaciones aplicables. Eres responsable de mantener la confidencialidad de tus credenciales de acceso y de todas las actividades realizadas bajo tu cuenta.", "terms.s5.title": "5. Limitación de Responsabilidad", "terms.s5.body": "Privaro se proporciona 'tal cual' sin garantías de ningún tipo. En la máxima medida permitida por la ley, iCommunity Labs & Tech S.L. no será responsable de daños indirectos, incidentales o consecuentes derivados del uso del servicio.", "terms.s6.title": "6. Legislación Aplicable", "terms.s6.body": "Estos términos se rigen por la legislación española. Cualquier disputa estará sujeta a la jurisdicción exclusiva de los tribunales de Madrid, España.",
    "auth.signin": "Iniciar sesión", "auth.signup": "Crear cuenta", "auth.forgot": "Restablecer contraseña", "auth.signin.desc": "Accede a tu panel de privacidad", "auth.signup.desc": "Configura tu organización", "auth.forgot.desc": "Te enviaremos un enlace de restablecimiento", "auth.email": "Correo electrónico", "auth.password": "Contraseña", "auth.orgName": "Nombre de la organización", "auth.fullName": "Nombre completo", "auth.forgotLink": "¿Olvidaste tu contraseña?", "auth.sendReset": "Enviar enlace", "auth.sending": "Enviando...", "auth.loading": "Cargando...", "auth.backToSignin": "Volver a iniciar sesión", "auth.noAccount": "¿No tienes cuenta?", "auth.hasAccount": "¿Ya tienes cuenta?", "auth.accountCreated": "Cuenta creada", "auth.checkEmail": "Revisa tu correo para verificar tu cuenta y luego inicia sesión.", "auth.emailSent": "Correo enviado", "auth.checkInbox": "Revisa tu bandeja de entrada para el enlace de restablecimiento.",
    "emailConfirmed.title": "¡Cuenta verificada!", "emailConfirmed.desc": "Tu correo ha sido confirmado correctamente. Ya puedes iniciar sesión en tu cuenta.", "emailConfirmed.redirect": "Redirigiendo al inicio de sesión…",
    "reset.title": "Restablece tu contraseña", "reset.desc": "Introduce tu nueva contraseña", "reset.newPassword": "Nueva contraseña", "reset.confirmPassword": "Confirmar contraseña", "reset.update": "Actualizar contraseña", "reset.updating": "Actualizando...", "reset.verifying": "Verificando enlace…", "reset.noMatch": "Las contraseñas no coinciden", "reset.success": "Contraseña actualizada", "reset.successDesc": "Ya puedes iniciar sesión con tu nueva contraseña.",
    "secpage.hero.badge": "Seguridad y Cumplimiento",
    "secpage.hero.title1": "Seguridad de nivel empresarial",
    "secpage.hero.title2": "por diseño, no por política",
    "secpage.hero.desc": "La infraestructura de privacidad de Privaro se basa en el principio de que los controles de seguridad deben ser arquitectónicos — no parches a nivel de aplicación.",
    "secpage.badge.aes": "Cifrado AES-256-GCM",
    "secpage.badge.blockchain": "Registro de auditoría certificado en blockchain",
    "secpage.badge.gdpr": "Compatible con RGPD Art.5",
    "secpage.badge.tls": "TLS 1.3 aplicado",
    "secpage.badge.soc2": "SOC2 Tipo I — En preparación",
    "secpage.badge.iso": "ISO 27001 — En preparación",
    "secpage.arch.label": "Arquitectura",
    "secpage.arch.title": "Seguridad integrada en cada capa",
    "secpage.arch.desc": "Los controles de privacidad se aplican en la capa de red — antes de que cualquier dato llegue a un modelo de IA. Esto es arquitectónicamente superior al post-procesamiento o filtrado a nivel de aplicación.",
    "secpage.pillar1.title": "Cero exposición de datos personales en texto plano",
    "secpage.pillar1.desc": "Ningún dato personal en texto plano se transmite jamás a un proveedor de IA. La tokenización ocurre dentro del perímetro de confianza de Privaro. Los valores originales se almacenan exclusivamente en la bóveda cifrada.",
    "secpage.pillar2.title": "Evidencia de cumplimiento verificable",
    "secpage.pillar2.desc": "Los registros de auditoría se certifican criptográficamente en Fantom Opera Mainnet. El cumplimiento es demostrable ante reguladores de forma independiente a la infraestructura de Privaro.",
    "secpage.pillar3.title": "Defensa en profundidad",
    "secpage.pillar3.desc": "Los controles de seguridad están en capas: TLS 1.3 a nivel de red, JWT + API key a nivel de aplicación, Row Level Security a nivel de base de datos, AES-256-GCM a nivel de datos.",
    "secpage.pillar4.title": "Gobernanza basada en políticas",
    "secpage.pillar4.desc": "Cada tipo de entidad tiene una acción configurable: tokenizar, anonimizar o bloquear. Presets sectoriales para Legal, Salud, Fintech, RRHH y Port Environmental incluidos.",
    "secpage.pillar5.title": "Gobernanza de agentes",
    "secpage.pillar5.desc": "Los agentes de IA autónomos operan bajo las mismas políticas de privacidad que los usuarios humanos. La API de agentes aplica gobernanza en cada paso de los flujos automatizados — compatible con EU AI Act.",
    "secpage.pillar6.title": "Residencia de datos en la UE",
    "secpage.pillar6.desc": "Toda la infraestructura se aloja en regiones de la UE por defecto. Base de datos en eu-central-1, proxy en europe-west4. Ningún dato sale de la UE sin configuración explícita del cliente.",
    "secpage.controls.label": "Controles",
    "secpage.controls.title": "Controles de seguridad implementados",
    "secpage.controls.desc": "Controles técnicos clave alineados con ISO/IEC 27001:2022 Anexo A y los criterios de servicios de confianza de SOC2.",
    "secpage.ctrl1.desc": "Cifrado AES-256-GCM para todos los originales de tokens. Nonce aleatorio de 12 bytes por operación. Segmentación de claves por organización.",
    "secpage.ctrl2.desc": "Row Level Security aplica aislamiento por organización a nivel de base de datos. Todas las consultas filtradas por org_id.",
    "secpage.ctrl3.desc": "Claves API almacenadas como hashes SHA-256. El texto plano nunca se persiste. Verificación JWT en todas las llamadas del frontend.",
    "secpage.ctrl4.desc": "Registros de auditoría inmutables con certificación blockchain. UPDATE restringido a columnas ibs_* únicamente vía política RLS.",
    "secpage.ctrl5.desc": "TLS 1.3 aplicado en todas las conexiones. TLS 1.0 y 1.1 no aceptados. CORS configurado por entorno.",
    "secpage.ctrl6.desc": "Registro de auditoría certificado en blockchain. Cada interacción con datos personales genera un registro a prueba de manipulaciones en Fantom Opera Mainnet.",
    "secpage.ctrl7.desc": "Modelo de cuatro roles: viewer, developer, dpo, admin. Permisos acumulativos aplicados a nivel de BD, no de aplicación.",
    "secpage.ctrl8.desc": "Ciclo de vida de desarrollo seguro: revisión de código en GitHub, pipeline de despliegue en Railway, health checks automatizados.",
    "secpage.status.implemented": "✓ Implementado",
    "secpage.status.progress": "⟳ En progreso",
    "secpage.compliance.label": "Cumplimiento",
    "secpage.compliance.title": "Cobertura regulatoria",
    "secpage.compliance.desc": "Privaro está diseñado para ayudar a los clientes empresariales a cumplir con sus obligaciones de protección de datos bajo múltiples marcos regulatorios.",
    "secpage.table.regulation": "Regulación",
    "secpage.table.scope": "Ámbito",
    "secpage.table.coverage": "Cobertura Privaro",
    "secpage.table.status": "Estado",
    "secpage.reg1.scope": "Minimización de datos, limitación de finalidad",
    "secpage.reg1.coverage": "El motor de políticas aplica el procesamiento mínimo necesario. Ningún dato personal en texto plano a LLMs.",
    "secpage.reg2.scope": "Datos de categoría especial (salud, biométricos)",
    "secpage.reg2.coverage": "La entidad health_record se bloquea o anonimiza por defecto en los presets de Salud/RRHH.",
    "secpage.reg3.scope": "Registros de actividades de tratamiento",
    "secpage.reg3.coverage": "Registro de auditoría certificado en blockchain por interacción. Exportación de informe DPO con hashes de TX.",
    "secpage.reg4.scope": "Sistemas de IA de alto riesgo, supervisión humana",
    "secpage.reg4.coverage": "La API de agentes aplica gobernanza sobre agentes autónomos. Acción por entidad en los registros de auditoría.",
    "secpage.reg5.scope": "Protección de datos de pago",
    "secpage.reg5.coverage": "IBANs y números de tarjeta tokenizados antes de cualquier llamada a LLM. Preset Fintech incluido.",
    "secpage.reg6.scope": "Información sanitaria protegida",
    "secpage.reg6.coverage": "PHI tokenizada/anonimizada. Registro de auditoría blockchain por acceso a PHI. Preset Salud incluido.",
    "secpage.reg7.scope": "Gestión de seguridad de la información",
    "secpage.reg7.coverage": "83% de los controles del Anexo A implementados. Documentación SGSI en progreso.",
    "secpage.reg8.scope": "Criterios de confianza de Seguridad y Confidencialidad",
    "secpage.reg8.coverage": "Controles implementados. Preparación de auditoría formal en progreso para Q3 2026.",
    "secpage.status.covered": "Cubierto",
    "secpage.status.inprogress": "En progreso",
    "secpage.blockchain.label": "Registro de auditoría blockchain",
    "secpage.blockchain.title": "Evidencia de cumplimiento a prueba de manipulaciones",
    "secpage.blockchain.desc": "Cada evento de auditoría se certifica criptográficamente en Fantom Opera Mainnet — verificable de forma independiente por reguladores, auditores y titulares de datos.",
    "secpage.blockchain.howTitle": "Cómo funciona",
    "secpage.blockchain.howP1": "Cada evento de detección de datos personales genera un registro de auditoría. El hash SHA-512 del registro se certifica en Fantom Opera Mainnet vía iBS API. El hash de TX blockchain resultante se almacena en el registro de auditoría.",
    "secpage.blockchain.howP2": "La certificación por lotes reduce costes: hasta 100 eventos de auditoría se certifican en una sola transacción blockchain cada 5 minutos.",
    "secpage.blockchain.verifyTitle": "Verificabilidad pública",
    "secpage.blockchain.verifyDesc": "Cualquier evento certificado puede verificarse de forma independiente usando el hash de TX — sin necesidad de acceso a la infraestructura de Privaro.",
    "secpage.stat1.label": "Blockchain Opera Mainnet",
    "secpage.stat2.label": "Tiempo medio de certificación",
    "secpage.stat3.label": "Eficiencia por lote (eventos por TX)",
    "secpage.stat4.label": "Algoritmo de hashing",
    "secpage.docs.label": "Documentos de políticas",
    "secpage.docs.title": "Políticas y procedimientos de seguridad",
    "secpage.docs.desc": "Privaro mantiene un conjunto completo de políticas de seguridad alineadas con los requisitos de ISO 27001 y SOC2. Disponibles para clientes empresariales bajo NDA.",
    "secpage.doc1.title": "Política de seguridad de la información",
    "secpage.doc2.title": "Política de tratamiento de datos y privacidad",
    "secpage.doc3.title": "Registro de controles de seguridad (ISO 27001 Anexo A)",
    "secpage.doc4.title": "Plan de respuesta ante incidentes",
    "secpage.doc5.title": "Política de continuidad de negocio y disponibilidad",
    "secpage.doc6.title": "Acuerdo de tratamiento de datos (DPA)",
    "secpage.cta.title": "¿Preguntas sobre seguridad?",
    "secpage.cta.desc": "Nuestro equipo está disponible para responder cuestionarios de seguridad, completar evaluaciones de proveedores o programar una sesión técnica en profundidad.",
    "secpage.cta.contact": "Contactar equipo de seguridad",
    "secpage.cta.download": "Descargar documentos de políticas",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLangState] = useState<Language>(detectInitialLang);

  const setLang = (l: Language) => {
    setLangState(l);
    localStorage.setItem("privaro-lang", l);
  };

  const t = (key: string): string => {
    return translations[lang][key] ?? translations["en"][key] ?? key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
};