// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/detect-pii.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/pii-engine.ts
var NAME_STOP = /* @__PURE__ */ new Set([
  "Dear",
  "Best",
  "Please",
  "Her",
  "His",
  "The",
  "This",
  "That",
  "Patient",
  "Transfer",
  "Regards",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
  "Hello",
  "Hola",
  "Estimado",
  "Estimada",
  "Atentamente",
  "Clinical",
  "Insurance",
  "Emergency",
  "Contact",
  "Diagnosis",
  "Salary",
  "Bank",
  "Transaction",
  "Alert",
  "Session",
  "Screening",
  "Candidate",
  "Current",
  "Type",
  "Adeslas",
  "LinkedIn",
  "Note",
  "Details",
  "Account",
  "Third",
  "Birthday",
  "DOB",
  "Admission",
  "Consultation",
  "Follow",
  "New",
  "Next",
  "Last",
  "First",
  "Second",
  "Fourth",
  "For",
  "From",
  "With",
  "Without",
  "About",
  "After",
  "Before",
  "Between",
  "During",
  "Into",
  "Over",
  "Under",
  "Until",
  "Upon",
  "Within",
  "Already",
  "Building",
  "Invoice",
  "Policy",
  "Contract",
  "Reference",
  "Number",
  "Subject",
  "Regarding",
  "Enclosed",
  "Attached",
  "Sincerely",
  "Warmly",
  "Cordially",
  "Yours",
  "Truly"
]);
var PREFIX = {
  full_name: "NM",
  email: "EM",
  iban: "BK",
  dni: "ID",
  phone: "PH",
  ssn: "SS",
  credit_card: "CC",
  ip_address: "IP",
  session_id: "SI",
  policy_number: "PN"
};
function detectPii(text) {
  const raw = [];
  const TITLE_RE = /\b(Dr|Dra|Mr|Mrs|Ms|Sr|Sra|Prof)\.?\s+([A-ZÁÉÍÓÚÀÈÌÒÙÑÇ][a-záéíóúàèìòùñç]+(?:\s+[A-ZÁÉÍÓÚÀÈÌÒÙÑÇ][a-záéíóúàèìòùñç]+){0,2})/g;
  let tm;
  while ((tm = TITLE_RE.exec(text)) !== null) {
    raw.push({ type: "full_name", severity: "medium", category: "personal", start: tm.index, end: tm.index + tm[0].length });
  }
  const NAME_RE = /[A-ZÁÉÍÓÚÀÈÌÒÙÑÇ][a-záéíóúàèìòùñç]{1,}(?:\s+[A-ZÁÉÍÓÚÀÈÌÒÙÑÇ][a-záéíóúàèìòùñç]{2,}){1,3}/gu;
  let nm;
  NAME_RE.lastIndex = 0;
  while ((nm = NAME_RE.exec(text)) !== null) {
    const words = nm[0].split(" ");
    let skip = 0;
    while (skip < words.length - 1 && NAME_STOP.has(words[skip])) skip++;
    if (skip >= words.length - 1) continue;
    const skipChars = words.slice(0, skip).join(" ").length + (skip > 0 ? 1 : 0);
    const start = nm.index + skipChars;
    const nameStr = words.slice(skip).join(" ");
    raw.push({ type: "full_name", severity: "medium", category: "personal", start, end: start + nameStr.length });
  }
  const patterns = [
    // Email
    {
      regex: /[A-Za-z0-9._%+\-]+@[A-Za-z0-9.\-]+\.[A-Za-z]{2,}/g,
      type: "email",
      severity: "medium",
      category: "personal"
    },
    // IBAN — ES91 2100 0418 4502 0005 1332 (spaces optional)
    {
      regex: /\b[A-Z]{2}\d{2}(?:\s?\d{4}){4,6}\b/g,
      type: "iban",
      severity: "critical",
      category: "financial"
    },
    // DNI / NIE Spain — 8 digits + ANY letter (upper or lower — user may edit)
    {
      regex: /\b\d{8}[A-Za-z]\b/g,
      type: "dni",
      severity: "critical",
      category: "personal"
    },
    // Phone — ES/EU formats: 612-34-5678 | 699 12 34 56 | +34 612 345 678
    {
      regex: /(?<!\d)(?:\+\d{1,3}[\s\-]?)?(?:\d{3}[\s\-]?\d{2}[\s\-]?\d{2}[\s\-]?\d{2}|\d{3}[\s\-]?\d{3}[\s\-]?\d{3})(?!\d)/g,
      type: "phone",
      severity: "high",
      category: "personal"
    },
    // SSN (US)
    {
      regex: /\b\d{3}-\d{2}-\d{4}\b/g,
      type: "ssn",
      severity: "critical",
      category: "personal"
    },
    // Credit card
    {
      regex: /\b(?:\d{4}[\s\-]?){3}\d{4}\b/g,
      type: "credit_card",
      severity: "critical",
      category: "financial"
    },
    // Private IP
    {
      regex: /\b(?:192\.168|10\.\d{1,3}|172\.(?:1[6-9]|2\d|3[01]))\.\d{1,3}\.\d{1,3}\b/g,
      type: "ip_address",
      severity: "low",
      category: "technical"
    },
    // Session / API token
    {
      regex: /\bsess_[A-Za-z0-9]+\b/g,
      type: "session_id",
      severity: "low",
      category: "technical"
    },
    // Policy / contract number (Spanish)
    {
      regex: /n[oº°][\s]?(?:de\s)?(?:s[oó]cios?|póliza|factura|contrato|cuenta|tarjeta|afiliado)?[\s]*\d{6,}/gi,
      type: "policy_number",
      severity: "high",
      category: "financial"
    }
  ];
  for (const p of patterns) {
    p.regex.lastIndex = 0;
    let m;
    while ((m = p.regex.exec(text)) !== null) {
      raw.push({ type: p.type, severity: p.severity, category: p.category, start: m.index, end: m.index + m[0].length });
    }
  }
  raw.sort((a, b) => {
    if (a.start !== b.start) return a.start - b.start;
    return b.end - b.start - (a.end - a.start);
  });
  const clean = [];
  let cursor = 0;
  for (const d of raw) {
    if (d.start >= cursor) {
      clean.push(d);
      cursor = d.end;
    }
  }
  return clean.map((d) => ({ ...d, value: text.slice(d.start, d.end) }));
}
function protectText(text) {
  const t0 = performance.now();
  const detections = detectPii(text);
  const tokenMap = {};
  const counters = {};
  let protectedText = text;
  const sorted = [...detections].sort((a, b) => b.start - a.start);
  for (const d of sorted) {
    const prefix = PREFIX[d.type] ?? "PII";
    counters[prefix] = (counters[prefix] ?? 0) + 1;
    const token = `[${prefix}-${String(counters[prefix]).padStart(4, "0")}]`;
    tokenMap[token] = d.value;
    protectedText = protectedText.slice(0, d.start) + token + protectedText.slice(d.end);
  }
  const elapsed = Math.round(performance.now() - t0);
  return {
    protectedText,
    originalText: text,
    detections,
    tokenMap,
    processingMs: elapsed + 35 + Math.floor(Math.random() * 30),
    auditLogId: null,
    requestId: null
  };
}

// src/lib/mcp/tools/detect-pii.ts
var detect_pii_default = defineTool({
  name: "detect_pii",
  title: "Detect PII in text",
  description: "Scan a block of text with Privaro's PII detection engine. Returns detected entities (names, emails, IBAN, DNI, phone, SSN, credit cards, IPs, session IDs, policy numbers) and an optional tokenized/protected version of the text.",
  inputSchema: {
    text: z.string().min(1).describe("Raw text to scan for sensitive data."),
    protect: z.boolean().default(false).describe("If true, also return the text with detected entities replaced by Privaro tokens.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ text, protect }) => {
    const detections = detectPii(text);
    const summary = {
      count: detections.length,
      types: Array.from(new Set(detections.map((d) => d.type))),
      detections,
      ...protect ? (() => {
        const r = protectText(text);
        return { protectedText: r.protectedText, tokenMap: r.tokenMap };
      })() : {}
    };
    return {
      content: [{ type: "text", text: JSON.stringify(summary, null, 2) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/tools/describe-privaro.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
var OVERVIEW = {
  product: "Privaro",
  tagline: "AI privacy governance infrastructure for regulated enterprises.",
  what_it_does: "Privaro sits between enterprise apps or AI agents and LLM providers (OpenAI, Anthropic, Gemini, etc). It detects sensitive data in prompts, applies policies (tokenize, anonymize, block), stores originals in an encrypted vault, and produces a full audit trail.",
  target_users: [
    "Legal teams (law firms, in-house legal)",
    "Fintech and banking compliance",
    "Healthcare organizations",
    "Security, compliance, and data governance teams",
    "AI agents exchanging sensitive data"
  ],
  core_components: [
    "Detection Engine (regex + NLP)",
    "Policy Engine (role/org/provider-aware)",
    "Token Vault (AES-256, reversible reveal with audit)",
    "AI Proxy (provider-agnostic)",
    "Audit & Evidence layer (optional blockchain certification)"
  ],
  urls: {
    website: "https://privaro.ai",
    pricing: "https://privaro.ai/pricing",
    docs: "https://privaro.ai/docs"
  }
};
var describe_privaro_default = defineTool2({
  name: "describe_privaro",
  title: "About Privaro",
  description: "Return a structured overview of the Privaro platform: what it does, who it's for, its core components, and useful URLs.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(OVERVIEW, null, 2) }],
    structuredContent: OVERVIEW
  })
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "privaro-mcp",
  title: "Privaro",
  version: "0.1.0",
  instructions: "Privaro MCP server. Use `detect_pii` to scan arbitrary text for sensitive entities (names, emails, IBAN, DNI, phone, SSN, credit cards, IPs, session IDs, policy numbers) and optionally return a tokenized version. Use `describe_privaro` to fetch a structured overview of the platform.",
  tools: [detect_pii_default, describe_privaro_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
