// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/detect-pii.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
import { detectPii, protectText } from "npm:@/lib/pii-engine";
var detect_pii_default = defineTool({
  name: "detect_pii",
  title: "Detect PII in text",
  description: "Scan a block of text with Privaro's PII detection engine. Returns detected entities (names, emails, IBAN, DNI, phone, SSN, credit cards, IPs, session IDs, policy numbers) and an optional tokenized/protected version of the text.",
  inputSchema: {
    text: z.string().min(1).describe("Raw text to scan for sensitive data."),
    protect: z.boolean().default(false).describe("If true, also return the text with detected entities replaced by Privaro tokens.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ text, protect }) => {
    const detections = detectPii(text);
    const summary = {
      count: detections.length,
      types: Array.from(new Set(detections.map((d) => d.type))),
      detections,
      ...protect ? (() => {
        const r = protectText(text);
        return { protectedText: r.protectedText, tokenMap: r.tokenMap };
      })() : {}
    };
    return {
      content: [{ type: "text", text: JSON.stringify(summary, null, 2) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/tools/describe-privaro.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
var OVERVIEW = {
  product: "Privaro",
  tagline: "AI privacy governance infrastructure for regulated enterprises.",
  what_it_does: "Privaro sits between enterprise apps or AI agents and LLM providers (OpenAI, Anthropic, Gemini, etc). It detects sensitive data in prompts, applies policies (tokenize, anonymize, block), stores originals in an encrypted vault, and produces a full audit trail.",
  target_users: [
    "Legal teams (law firms, in-house legal)",
    "Fintech and banking compliance",
    "Healthcare organizations",
    "Security, compliance, and data governance teams",
    "AI agents exchanging sensitive data"
  ],
  core_components: [
    "Detection Engine (regex + NLP)",
    "Policy Engine (role/org/provider-aware)",
    "Token Vault (AES-256, reversible reveal with audit)",
    "AI Proxy (provider-agnostic)",
    "Audit & Evidence layer (optional blockchain certification)"
  ],
  urls: {
    website: "https://privaro.ai",
    pricing: "https://privaro.ai/pricing",
    docs: "https://privaro.ai/docs"
  }
};
var describe_privaro_default = defineTool2({
  name: "describe_privaro",
  title: "About Privaro",
  description: "Return a structured overview of the Privaro platform: what it does, who it's for, its core components, and useful URLs.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(OVERVIEW, null, 2) }],
    structuredContent: OVERVIEW
  })
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "privaro-mcp",
  title: "Privaro",
  version: "0.1.0",
  instructions: "Privaro MCP server. Use `detect_pii` to scan arbitrary text for sensitive entities (names, emails, IBAN, DNI, phone, SSN, credit cards, IPs, session IDs, policy numbers) and optionally return a tokenized version. Use `describe_privaro` to fetch a structured overview of the platform.",
  tools: [detect_pii_default, describe_privaro_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
